### ISSUE TITLE
Running an_util.py: sqlite3.OperationalError

### ISSUE THREAD

**Issue by DK2BN** [n8acl/aprsnotify#8]
Hi, thank you for your work!

I'm trying to setup aprsnotify for the first time.

```
root@raspberry:/opt/aprsnotify# python3 an_util.py 
Traceback (most recent call last):
  File "an_util.py", line 157, in <module>
    new(conn, current_version)
  File "an_util.py", line 127, in new
    exec_sql(conn,sql)
  File "an_util.py", line 33, in exec_sql
    cur.execute(sql)
sqlite3.OperationalError: 18 values for 19 columns
```

**Comment by n8acl** [comment]
I'm sorry I never got notified of this. I will have to take a look and see what is going on.

**Comment by n8acl** [comment]
This is old and will be closed. With the new version of APRSNotify, this should be rectified...
